### ISSUE TITLE
The argument type 'BlocProvider<WeatherCubit>' can't be assigned to the parameter type 'Widget'

### ISSUE THREAD

**Issue by Alecckie** [ResoCoder/flutter-bloc-cubit-tutorial#2]
There seems to be an issue using the BlocProvider in the latest version of Flutter.
i.e 
bloc: ^6.1.0
flutter_bloc: ^6.1.1
It just wont allow usage of BlocProvider in the main.dart file.
This is even after I literally copy paste your codes to ensure no errors on my side. I am literally scratching my head over this since I very much need this functionality.
Error thrown: **The argument type 'BlocProvider<WeatherCubit>' can't be assigned to the parameter type 'Widget'**

If I try to compile without the BlocProvider, then:
New Error: 
`/C:/Users/Lefty2020/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/provider-4.3.2+3/lib/single_child_widget.dart:1:1: Error: Error when reading '/C:/Users/Lefty2020/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/nested-0.0.4/lib/nested.dart': The system cannot find the path specified.

export 'package:nested/nested.dart' hide Nested;`

**Comment by alexjeanderae** [comment]
Thanks for mentioning the issue - here on stackoverflow I assume is your other posting of the issue. That one has a solution to it. Probably this one  can be closed.
